name = "stunnas-tweaks"
type = "javascript"
account_id = "64197f09b6a634cc20011f6350eed667"
workers_dev = true
compatibility_date = "2024-02-23"

[build]
command = "npm run build"
upload.format = "service-worker"
upload.dir = "dist"